application:
  seed:
    dataurl: https://gist.github.com/armgilles/194bcff35001e7eb53a2a8b441e8b2c6


spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect